### ISSUE TITLE
Loading package Problems

### ISSUE THREAD

**Issue by NoeCors** [andrewraim/COMMultReg#2]
Hi @andrewraim, 
I am trying to load this package in R following your suggested commands but I always get an error and so I am not able to load it. I tried in many different ways (creating a project, downloading the package in my pc, running different packages like roxygen2 in advance...) but it still doesn't work... I think there may be a problem somewhere... can you solve it?
Thanks in advance for your time

**Comment by andrewraim** [comment]
Dear @NoeCors,

I just tried the steps from the README (from within R):

```r
library(devtools)
install_github("andrewraim/COMMultReg")
```

The installation also failed for me at the very end, saying that it couldn't find some functions in the namespace. I think some of the autogenerated Rcpp stuff (RcppExports.cpp and RcppExports.R) needed to be added to Github. After doing that, the `install_github` step works for me.

I am going to mark this as closed for now, but give it another try and let me know if you still have problems. If so, it will help if you note down particular steps you've taken and any error messages you are seeing.

Best,
Andrew
